name: Publish production
on:
  workflow_dispatch: {}
  push:
    branches: [master]
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Github packages
        uses: docker/login-action@v3
        with:
          username: duncte123
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: oengusio/timers:latest
          cache-from: type=gha
          cache-to: type=gha

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

      - name: Trigger dev webhook
        uses: distributhor/workflow-webhook@v3
        env:
          webhook_url: ${{ secrets.PROD_WEBHOOK_URL }}
